### ISSUE TITLE
Pods don't seem to get the port env-vars they need

### ISSUE THREAD

**Issue by TBBle** [cyber-dojo/k8s-install#9]
Firstly, I noticed _model_ isn't part of the install script, but I suspect that's just because it was only (re-)added into the full system recently. I trivially resolved that just by copying the existing two blocks for _differ_.

However, I then hit a more-complex issue.

It seems that none of the services receive the `CYBER_DOJO_XXX_PORT` env-vars they need to talk to the other services, causing them to attempt to talk on port 0.

A few pods (model, differ, and creator) fail to start because of this, but after adding the env-vars by hand, I found that `KataController#edit` then failed trying to talk to port 0 on saver, so I have to assume not every pod is checking its necessary ports at startup.

More to the point, it's not clear how this is _intended_ to work. I don't see anything attempting to set env-vars for the ports of the other services in the scripts, so it's not clear to me what's broken, so it's not as simple a fix as the other issues I've noticed giving this a burl today.

In case I or someone else comes looking for this later, I worked around this by adding the below block to almost all the '*-k8s-general-values.yml' files in the installer dir, before `volumeMounts` in the container definition.
```yaml
    env:
      CYBER_DOJO_PROMETHEUS: "true"
      CYBER_DOJO_CUSTOM_START_POINTS_PORT: "4526"
      CYBER_DOJO_EXERCISES_START_POINTS_PORT: "4525"
      CYBER_DOJO_LANGUAGES_START_POINTS_PORT: "4524"
      CYBER_DOJO_CREATOR_PORT: "4523"
      CYBER_DOJO_MODEL_PORT: "4528"
      CYBER_DOJO_DIFFER_PORT: "4567"
      CYBER_DOJO_REPLER_PORT: "4657"
      CYBER_DOJO_RUNNER_PORT: "4597"
      CYBER_DOJO_SAVER_PORT: "4537"
      CYBER_DOJO_SHAS_PORT: "4522"
      CYBER_DOJO_WEB_PORT: "3000"
```
